// @vitest-environment jsdom

import { beforeEach, describe, expect, it } from "vitest";
import { highlightCodeBlocks } from "./code-highlighter.js";

describe("code-highlighter", () => {
  beforeEach(() => {
    document.body.innerHTML = "";
  });

  it("highlights javascript code block and marks banner as sticky", () => {
    const container = document.createElement("div");
    container.innerHTML = `
      <div class="md-code-block">
        <div class="md-code-block-banner">javascript <span>Copy</span></div>
        <pre><code class="language-js">const x = 42;</code></pre>
      </div>
    `;
    document.body.appendChild(container);

    highlightCodeBlocks(container);

    const banner = container.querySelector(".md-code-block-banner");
    expect(banner.classList.contains("bds-code-sticky-banner")).toBe(true);

    const code = container.querySelector("code");
    expect(code.getAttribute("data-bds-highlighted")).toBe("1");
    // Token span generated by Prism
    expect(code.querySelector(".token")).toBeTruthy();
  });

  it("handles python code block", () => {
    const container = document.createElement("div");
    container.innerHTML = `
      <div class="md-code-block">
        <div class="md-code-block-banner">Python</div>
        <pre><code>def greet(name):\n    return f"Hello {name}"</code></pre>
      </div>
    `;
    document.body.appendChild(container);

    highlightCodeBlocks(container);

    const code = container.querySelector("code");
    expect(code.querySelector(".token.keyword")?.textContent).toBe("def");
  });
});
